import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Terms and Conditions - Merge Tools",
    description: "Terms and Conditions of use for Merge Tools utilities.",
};

export default function TermsPage() {
    return (
        <div className="mx-auto max-w-4xl space-y-8 pb-12">
            <div className="space-y-4">
                <h1 className="text-4xl font-bold tracking-tight md:text-5xl">Terms and Conditions</h1>
                <p className="text-muted-foreground">Last Updated: October 2023</p>
            </div>

            <div className="prose prose-slate dark:prose-invert max-w-none">
                <p>
                    Welcome to Merge Tools! These terms and conditions outline the rules and regulations for the use of our website.
                </p>
                <p>
                    By accessing this website we assume you accept these terms and conditions. Do not continue to use Merge Tools if
                    you do not agree to take all of the terms and conditions stated on this page.
                </p>

                <h2>1. Services Provided</h2>
                <p>
                    Merge Tools provides a collection of free online utility tools (the "Services"). These tools are provided "as is" and
                    "as available". While we strive for accuracy, we do not guarantee that the results generated by our tools are
                    100% accurate, complete, or suitable for any particular purpose.
                </p>

                <h2>2. Acceptable Use</h2>
                <p>
                    You must not use this website in any way that causes, or may cause, damage to the website or impairment of the
                    availability or accessibility of Merge Tools; or in any way which is unlawful, illegal, fraudulent, or harmful.
                </p>
                <p>
                    Automated scraping, API abuse, or using bots to aggressively query our tools is strictly prohibited and may
                    result in your IP being blocked.
                </p>

                <h2>3. Disclaimer of Warranties and Liability</h2>
                <p>
                    The tools and information on this website are provided free of charge. We will not be liable for any loss or damage
                    of any nature. Under no circumstances shall Merge Tools be liable for any direct, indirect, special, incidental or
                    consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the
                    inability to use, the materials on this site.
                </p>

                <h2>4. Advertising</h2>
                <p>
                    Merge Tools displays third-party advertisements (such as Google AdSense) to keep our services free. By using our site,
                    you acknowledge that these ads may be displayed. You agree not to use ad-clicking bots or artificially inflate
                    ad impressions.
                </p>

                <h2>5. Modifications</h2>
                <p>
                    Merge Tools reserves the right to revise these terms at any time without notice. By using this website you are
                    agreeing to be bound by the then current version of these Terms and Conditions.
                </p>
            </div>
        </div>
    );
}
