import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Disclaimer - DevPik",
    description: "Disclaimer for DevPik. Understand the limitations and terms of using our free online tools.",
};

export default function DisclaimerPage() {
    return (
        <div className="mx-auto max-w-4xl space-y-8 pb-12">
            <div className="space-y-4">
                <h1 className="text-4xl font-bold tracking-tight md:text-5xl">Disclaimer</h1>
                <p className="text-muted-foreground">Last Updated: February 2026</p>
            </div>

            <div className="prose prose-slate max-w-none">
                <p>
                    The information and tools provided on DevPik (accessible at{" "}
                    <Link href="https://devpik.com" className="text-primary hover:underline">devpik.com</Link>)
                    are for general informational and utility purposes only.
                </p>

                <h2>1. No Warranties</h2>
                <p>
                    All tools on this website are provided &quot;as is&quot; and &quot;as available&quot; without any warranties
                    of any kind, either express or implied, including but not limited to implied warranties of merchantability,
                    fitness for a particular purpose, or non-infringement. While we strive to ensure accuracy, we do not warrant
                    or guarantee that the results generated by any tool are accurate, complete, reliable, or suitable for any
                    specific purpose.
                </p>

                <h2>2. Not Professional Advice</h2>
                <p>
                    The tools on this website do not constitute professional, legal, medical, financial, or technical advice.
                    For critical applications, always consult a qualified professional and verify results independently.
                </p>

                <h2>3. Limitation of Liability</h2>
                <p>
                    Under no circumstances shall DevPik, its owners, employees, or affiliates be liable for any direct,
                    indirect, incidental, special, consequential, or punitive damages arising from the use of, or inability
                    to use, the tools or information provided on this website. This includes, but is not limited to, loss of
                    data, revenue, or profits, even if DevPik has been advised of the possibility of such damages.
                </p>

                <h2>4. Accuracy of Conversions and Calculations</h2>
                <p>
                    Tools that perform unit conversions, color conversions, encoding/decoding, or any mathematical calculations
                    use industry-standard formulas and algorithms. However, rounding errors, floating-point precision limitations,
                    or browser-specific behavior may cause minor discrepancies. Always verify critical calculations through
                    independent sources.
                </p>

                <h2>5. Third-Party Content</h2>
                <p>
                    This website may contain links to third-party websites or services. DevPik has no control over the
                    content, privacy policies, or practices of any third-party sites and assumes no responsibility for them.
                    We strongly encourage you to review the terms and privacy policies of any third-party sites you visit.
                </p>

                <h2>6. Changes to This Disclaimer</h2>
                <p>
                    We reserve the right to modify this Disclaimer at any time without prior notice. Changes are effective
                    immediately upon posting. Your continued use of the website constitutes acceptance of the revised Disclaimer.
                </p>

                <h2>7. Contact</h2>
                <p>
                    If you have any questions about this Disclaimer, please contact us at{" "}
                    <a href="mailto:founders@mergemain.com" className="text-primary hover:underline">founders@mergemain.com</a>.
                </p>
            </div>
        </div>
    );
}
